### ISSUE TITLE
Descargar y convertir banderas 

### ISSUE THREAD

**Issue by ircsasw** [ircsasw/quiniela#1]
Descargar las banderas de cada equipo en formato .PNG desde: [banderas](http://es.fifa.com/worldcup/groups/)

![image](https://user-images.githubusercontent.com/919978/39338211-2050c1ae-4987-11e8-9c4d-a22661aafd76.png)

Convertir cada bandera en base64 desde: [encoding](https://www.base64-image.de/)

![image](https://user-images.githubusercontent.com/919978/39338238-47f84970-4987-11e8-864e-997358ccf276.png)

Copiar código en la tabla de equipos

![image](https://user-images.githubusercontent.com/919978/39338260-66a43ad2-4987-11e8-8ee4-bf6446c93c67.png)

Se debe de registrar un script de las actualizaciones para crear un migrate de forma que todos tengan las banderas en su base de datos local.

Agregar en el proyecto los archivos de las imágenes de las banderas .PNG

**Comment by AndreyPootMay** [comment]
Ya está listo.
