### ISSUE TITLE
Formato de fecha

### ISSUE THREAD

**Issue by ircsasw** [ircsasw/quiniela#8]
ahora se ve el panel de resultados de partidos con sólo la hora del juego

![image](https://user-images.githubusercontent.com/919978/41475676-03565742-7085-11e8-92e0-1bdfd43fe6e5.png)

cambiar el formato de: 10:00 
a: Jue 10AM

se hace con formatter, por ejemplo: 
`Yii::$app->formatter->asDate($printDate, 'php:D d/m')`

**Comment by AndreyPootMay** [comment]
![image](https://user-images.githubusercontent.com/28898216/41481692-869965e6-7098-11e8-9584-5fba6acc8f74.png)

**Comment by AndreyPootMay** [comment]
![image](https://user-images.githubusercontent.com/28898216/41481809-f99199ec-7098-11e8-9692-daf21d9bc582.png)
